/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mokleters
 */
public class Frame1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        StatusSpesialis = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Alamat = new javax.swing.JTextField();
        Usia = new javax.swing.JTextField();
        JenisKelamin = new javax.swing.JTextField();
        GolonganDarah = new javax.swing.JTextField();
        Status = new javax.swing.JTextField();
        Kewarganegaraan = new javax.swing.JTextField();
        WaktuPraktek = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PilihDokter = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Identitas"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StatusSpesialis.setEditable(false);
        StatusSpesialis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusSpesialisActionPerformed(evt);
            }
        });
        jPanel3.add(StatusSpesialis, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 170, 20));

        jLabel3.setText("Nama");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel4.setText("Status Spesialis");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        Nama.setEditable(false);
        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        jPanel3.add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 170, 20));

        Alamat.setEditable(false);
        Alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlamatActionPerformed(evt);
            }
        });
        jPanel3.add(Alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 170, 20));

        Usia.setEditable(false);
        Usia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsiaActionPerformed(evt);
            }
        });
        jPanel3.add(Usia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 170, 20));

        JenisKelamin.setEditable(false);
        JenisKelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JenisKelaminActionPerformed(evt);
            }
        });
        jPanel3.add(JenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 170, 20));

        GolonganDarah.setEditable(false);
        GolonganDarah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GolonganDarahActionPerformed(evt);
            }
        });
        jPanel3.add(GolonganDarah, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 170, 20));

        Status.setEditable(false);
        Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusActionPerformed(evt);
            }
        });
        jPanel3.add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 170, 20));

        Kewarganegaraan.setEditable(false);
        Kewarganegaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KewarganegaraanActionPerformed(evt);
            }
        });
        jPanel3.add(Kewarganegaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 170, 20));

        WaktuPraktek.setEditable(false);
        WaktuPraktek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaktuPraktekActionPerformed(evt);
            }
        });
        jPanel3.add(WaktuPraktek, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 170, 20));

        jLabel5.setText("Alamat");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel6.setText("Usia");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel7.setText("Jenis Kelamin");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel8.setText("Golongan Darah");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel9.setText("Status");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel10.setText("Kewarganegaraan");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel11.setText("Waktu Praktek");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 310, 300));

        jLabel1.setText("Pemilihan Dokter");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jLabel2.setText("Pilih Dokter");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        PilihDokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Salah Satu --", "DR. Farras Yassar", "DR. Anisa Putri", "DR. Harun Fajar" }));
        PilihDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilihDokterActionPerformed(evt);
            }
        });
        jPanel2.add(PilihDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 410));

        setBounds(0, 0, 418, 439);
    }// </editor-fold>//GEN-END:initComponents

    private void UsiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsiaActionPerformed

    private void AlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlamatActionPerformed

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void StatusSpesialisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusSpesialisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusSpesialisActionPerformed

    private void JenisKelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JenisKelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JenisKelaminActionPerformed

    private void GolonganDarahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GolonganDarahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GolonganDarahActionPerformed

    private void StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusActionPerformed

    private void KewarganegaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KewarganegaraanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KewarganegaraanActionPerformed

    private void WaktuPraktekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaktuPraktekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WaktuPraktekActionPerformed

    private void PilihDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilihDokterActionPerformed
       if(PilihDokter.getSelectedItem().equals("DR. Farras Yassar")){
           Nama.setText("DR. Farras Yassar ");
           Alamat.setText("Jl. Surabaya 16, Malang");
           Usia.setText("20 Tahun");
           JenisKelamin.setText("Laki-laki");
           GolonganDarah.setText("A");
           Status.setText("Belum Menikah");
           Kewarganegaraan.setText("Indonesia");
           StatusSpesialis.setText("Dokter Umum");
           WaktuPraktek.setText("Pagi (07.00-15.00)");
       }
       else if (PilihDokter.getSelectedItem().equals("DR. Anisa Putri")){
           Nama.setText("DR. Anisa Putri ");
           Alamat.setText("Jl. Veteran 3, Malang");
           Usia.setText("20 Tahun");
           JenisKelamin.setText("Perempuan");
           GolonganDarah.setText("O");
           Status.setText("Belum Menikah");
           Kewarganegaraan.setText("Indonesia");
           StatusSpesialis.setText("Dokter Gigi");
           WaktuPraktek.setText("Sore (16.00-22.00)");
       }
       else if (PilihDokter.getSelectedItem().equals("DR. Harun Fajar")){
           Nama.setText("DR. Harun Fajar ");
           Alamat.setText("Jl. Bandung 9, Malang");
           Usia.setText("20 Tahun");
           JenisKelamin.setText("Laki-laki");
           GolonganDarah.setText("B");
           Status.setText("Belum Menikah");
           Kewarganegaraan.setText("Indonesia");
           StatusSpesialis.setText("Dokter Gizi");
           WaktuPraktek.setText("Malam (22.00-06.00)");
       }
         
    }//GEN-LAST:event_PilihDokterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alamat;
    private javax.swing.JTextField GolonganDarah;
    private javax.swing.JTextField JenisKelamin;
    private javax.swing.JTextField Kewarganegaraan;
    private javax.swing.JTextField Nama;
    private javax.swing.JComboBox<String> PilihDokter;
    private javax.swing.JTextField Status;
    private javax.swing.JTextField StatusSpesialis;
    private javax.swing.JTextField Usia;
    private javax.swing.JTextField WaktuPraktek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
